// Socket event name constants — keep in sync with socket.types.ts
export const ROOM_EVENTS = {
  CREATE: 'room:create',
  JOIN: 'room:join',
  LEAVE: 'room:leave',
  ADD_BOT: 'room:addBot',
  REMOVE_BOT: 'room:removeBot',
  TOGGLE_READY: 'room:toggleReady',
  START_GAME: 'room:startGame',
  UPDATE_SETTINGS: 'room:updateSettings',
  CREATED: 'room:created',
  JOINED: 'room:joined',
  PLAYER_JOINED: 'room:playerJoined',
  PLAYER_LEFT: 'room:playerLeft',
  BOT_ADDED: 'room:botAdded',
  BOT_REMOVED: 'room:botRemoved',
  READY_CHANGED: 'room:readyChanged',
  SETTINGS_UPDATED: 'room:settingsUpdated',
  ERROR: 'room:error',
} as const;
