// Socket event name constants — keep in sync with socket.types.ts
export const ROOM_EVENTS = {
  CREATE: 'room:create',
  JOIN: 'room:join',
  LEAVE: 'room:leave',
  ADD_BOT: 'room:addBot',
  REMOVE_BOT: 'room:removeBot',
  TOGGLE_READY: 'room:toggleReady',
  START_GAME: 'room:startGame',
  UPDATE_SETTINGS: 'room:updateSettings',
  CREATED: 'room:created',
  JOINED: 'room:joined',
  PLAYER_JOINED: 'room:playerJoined',
  PLAYER_LEFT: 'room:playerLeft',
  BOT_ADDED: 'room:botAdded',
  BOT_REMOVED: 'room:botRemoved',
  READY_CHANGED: 'room:readyChanged',
  SETTINGS_UPDATED: 'room:settingsUpdated',
  ERROR: 'room:error',
} as const;

export const GAME_EVENTS = {
  PLACE_BET: 'game:placeBet',
  PLAY_CARD: 'game:playCard',
  PASS_CARDS: 'game:passCards',
  EXCHANGE_CARD: 'game:exchangeCard',
  DESIGNATE_PLAYER: 'game:designatePlayer',
  ACK_PEEK: 'game:acknowledgePeek',
  ACK_ROUND_END: 'game:ackRoundEnd',
  STARTED: 'game:started',
  PHASE_CHANGED: 'game:phaseChanged',
  MISSION_REVEALED: 'game:missionRevealed',
  CARDS_DEALT: 'game:cardsDealt',
  BET_PLACED: 'game:betPlaced',
  ALL_BETS_REVEALED: 'game:allBetsRevealed',
  BET_ERROR: 'game:betError',
  TURN_CHANGED: 'game:turnChanged',
  CARD_PLAYED: 'game:cardPlayed',
  PLAY_ERROR: 'game:playError',
  TRICK_WON: 'game:trickWon',
  CARDS_PASS_REQUIRED: 'game:cardsPassRequired',
  CARDS_RECEIVED: 'game:cardsReceived',
  EXCHANGE_REQUIRED: 'game:exchangeRequired',
  EXCHANGE_TARGETED: 'game:exchangeTargeted',
  DESIGNATE_REQUIRED: 'game:designateRequired',
  PEEK_START: 'game:peekStart',
  PEEK_END: 'game:peekEnd',
  HAND_UPDATE: 'game:handUpdate',
  ROUND_SCORING: 'game:roundScoring',
  ROUND_END: 'game:roundEnd',
  OVER: 'game:over',
  STATE_SYNC: 'game:stateSync',
  OPPONENT_HANDS_REVEALED: 'game:opponentHandsRevealed',
} as const;

export const PLAYER_EVENTS = {
  RECONNECT: 'player:reconnect',
  DISCONNECTED: 'player:disconnected',
  RECONNECTED: 'player:reconnected',
} as const;
